apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    project: karatu-2026-capstone
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::887930139017:role/project-bedrock-alb-controller-role
