apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-store-config
  namespace: {{ .Values.namespace }}
  labels:
    project: karatu-2025-capstone
data:
  mysql-host: {{ .Values.mysql.host }}
  postgres-host: {{ .Values.postgres.host }}
  dynamodb-table: {{ .Values.dynamodb.tableName }}
  region: {{ .Values.dynamodb.region }}
